on:
  push:
    branches:
      - master

name: Build documentation

jobs:
  jsdoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v2

    - name: Install JSDoc
      run: npm i jsdoc

    - name: Run JSDoc
      run: |
        node_modules/jsdoc/jsdoc.js src/ README.md -d docs/built/ -c docs/jsdoc.config.json

    - name: GH Pages Deployment
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/built
        target-folder: docs
        clean: true # Automatically remove deleted files from the deploy branch
